FROM python:3.11.3

ENV PYTHONUNBUFFERED 1

RUN apt update

RUN apt install zsh nano -y
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -y
RUN echo "zsh" >> ~/.bashrc 

WORKDIR /workspace
COPY requirements.txt /workspace

RUN pip install -r  requirements.txt

